### ISSUE TITLE
unable to update firmware post installation

### ISSUE THREAD

**Issue by arjun-k-r** [wilsomwong/Asus-TUF-FX504GE-Hackintosh#6]
12.1

after completing installation from USB , unable to update firmware window comes

**Comment by wilsomwong** [comment]
I also have this problem and I don't know where the problem happens ( stuck at 12.0 ) ...  I almost try my best to research a solution but not working and my Hackintosh laptop now also have a little problem ( I think my HDD is gonna die ). Okay first I will tell my story, I update it through the developer version from Big Sur to Monterey with some tricks ( I did not buy developer ), after that I realize that I can't update anymore it is stuck at 12.0  I think this is the problem that unable to receive an update any more ... I so sorry that I cannot fix this problem because I already try my best for any solution until my laptop HDD drive a little bit slow like boot-up has to wait 5 min ... Hope that you and the community can find a solution or just stay to use until having solution/firmware from another people. Thanks!

**Comment by wilsomwong** [comment]
Thanks for waiting, the latest EFI (Ventura EFI) already fix this problem. So pls download the lastest EFI for further updates, and the old EFI can throw into the trash because there have some bugs that I don't know have to fix, I already fix like almost one year.
